[W 20200413 09:22:43 base:170] Not Found: /
[I 20200413 09:22:51 views:22] 127.0.0.1已经存在
[I 20200413 09:22:58 views:22] 127.0.0.1已经存在
[I 20200413 09:23:59 views:22] 127.0.0.1已经存在
[E 20200413 09:23:59 base:256] Internal Server Error: /sendinfos/
Traceback (most recent call last):
  File "/Users/majianyu/Desktop/mydevops/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/majianyu/Desktop/mydevops/scanhosts/views.py", line 23, in user_info
    apf
NameError: name 'apf' is not defined
[I 20200413 09:24:29 views:22] 127.0.0.1已经存在
